env:
  browser: true
  es2021: true
settings:
  react:
    version: 'detect'
extends:
  - xo
  - plugin:react/recommended
  - prettier
  - plugin:promise/recommended
  - plugin:deprecation/recommended
overrides:
  - extends:
      - xo-typescript
    files:
      - '*.ts'
      - '*.tsx'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - prettier
  - promise
  - unused-imports
rules:
  react/prop-types: off
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: "^_"
      args: after-used
      argsIgnorePattern: "^_"
