stages:
  - lint
  - test
  - build
test-job:
  stage: test
  image: node:lts
  script:
    - npm install
    - npm run test
check-job:
  stage: lint
  image: node:lts
  script:
    - npm install
    - npm run lint

