name: Deploy to azure

env:
  APP_LOCATION: '/' # location of your client code
  API_LOCATION: 'api' # location of your api source code - optional
  OUTPUT_LOCATION: 'build' # location of client code build output
  CI: false
  AZURE_WEBAPP_NAME: shake-the-lake
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and trigger redeploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Trigger webook
        run: curl ${{ secrets.AZURE_WEBHOOK }} -H "" -d ""
